name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: npm ci && npm run test
        env:
          MAKEOBJ_PATH: /usr/lib/simutrans/makeobj
